export const Warnings = {
    FailedToFindChocolate : "Sorry, we couldn\'t find this chocolate",
    HelpFindChocolate : "Help us out by adding this new chocolate to our database!",
    ConfirmDeletion : "Are you sure you want to delete this item?",
    ErrorGettingImage : "An error occurred when we attempted to get your image",
    PasswordsDontMatch : "Passwords do not match", 
}

export const StringConcatenations = {
    Prefix: "BarcodeType_",
}

export const Colors = {
    Primary: "#4B006E"
}

export const dialogOptionsDatasets = {
    "cacaoVariety" : [
        { key: '*Cacao not mentioned' }, 
        { key: 'Criollo' }, 
        { key: 'Forastero' }, 
        { key: 'Trinitario' }, 
    ],

    "countryOfOrigin" : [
        { key: "Afghanistan"},
        { key: "Åland Islands"},
        { key: "Albania"},
        { key: "Algeria"},
        { key: "American Samoa"},
        { key: "Andorra"},
        { key: "Angola"},
        { key: "Anguilla"},
        { key: "Antarctica"},
        { key: "Antigua and Barbuda"},
        { key: "Argentina"},
        { key: "Armenia"},
        { key: "Aruba"},
        { key: "Australia"},
        { key: "Austria"},
        { key: "Azerbaijan"},
        { key: "Bahrain"},
        { key: "Bahamas"},
        { key: "Bangladesh"},
        { key: "Barbados"},
        { key: "Belarus"},
        { key: "Belgium"},
        { key: "Belize"},
        { key: "Benin"},
        { key: "Bermuda"},
        { key: "Bhutan"},
        { key: "Bolivia, Plurinational State of"},
        { key: "Bonaire, Sint Eustatius and Saba"},
        { key: "Bosnia and Herzegovina"},
        { key: "Botswana"},
        { key: "Bouvet Island"},
        { key: "Brazil"},
        { key: "British Indian Ocean Territory"},
        { key: "Brunei Darussalam"},
        { key: "Bulgaria"},
        { key: "Burkina Faso"},
        { key: "Burundi"},
        { key: "Cambodia"},
        { key: "Cameroon"},
        { key: "Canada"},
        { key: "Cape Verde"},
        { key: "Cayman Islands"},
        { key: "Central African Republic"},
        { key: "Chad"},
        { key: "Chile"},
        { key: "China"},
        { key: "Christmas Island"},
        { key: "Cocos (Keeling) Islands"},
        { key: "Colombia"},
        { key: "Comoros"},
        { key: "Congo"},
        { key: "Congo, the Democratic Republic of the"},
        { key: "Cook Islands"},
        { key: "Costa Rica"},
        { key: "Côte d'Ivoire"},
        { key: "Croatia"},
        { key: "Cuba"},
        { key: "Curaçao"},
        { key: "Cyprus"},
        { key: "Czech Republic"},
        { key: "Denmark"},
        { key: "Djibouti"},
        { key: "Dominica"},
        { key: "Dominican Republic"},
        { key: "Ecuador"},
        { key: "Egypt"},
        { key: "El Salvador"},
        { key: "Equatorial Guinea"},
        { key: "Eritrea"},
        { key: "Estonia"},
        { key: "Ethiopia"},
        { key: "Falkland Islands (Malvinas)"},
        { key: "Faroe Islands"},
        { key: "Fiji"},
        { key: "Finland"},
        { key: "France"},
        { key: "French Guiana"},
        { key: "French Polynesia"},
        { key: "French Southern Territories"},
        { key: "Gabon"},
        { key: "Gambia"},
        { key: "Georgia"},
        { key: "Germany"},
        { key: "Ghana"},
        { key: "Gibraltar"},
        { key: "Greece"},
        { key: "Greenland"},
        { key: "Grenada"},
        { key: "Guadeloupe"},
        { key: "Guam"},
        { key: "Guatemala"},
        { key: "Guernsey"},
        { key: "Guinea"},
        { key: "Guinea-Bissau"},
        { key: "Guyana"},
        { key: "Haiti"},
        { key: "Heard Island and McDonald Islands"},
        { key: "Holy See (Vatican City State)"},
        { key: "Honduras"},
        { key: "Hong Kong"},
        { key: "Hungary"},
        { key: "Iceland"},
        { key: "India"},
        { key: "Indonesia"},
        { key: "Iran, Islamic Republic of"},
        { key: "Iraq"},
        { key: "Ireland"},
        { key: "Isle of Man"},
        { key: "Israel"},
        { key: "Italy"},
        { key: "Jamaica"},
        { key: "Japan"},
        { key: "Jersey"},
        { key: "Jordan"},
        { key: "Kazakhstan"},
        { key: "Kenya"},
        { key: "Kiribati"},
        { key: "Korea, Democratic People's Republic of"},
        { key: "Korea, Republic of"},
        { key: "Kuwait"},
        { key: "Kyrgyzstan"},
        { key: "Lao People's Democratic Republic"},
        { key: "Latvia"},
        { key: "Lebanon"},
        { key: "Lesotho"},
        { key: "Liberia"},
        { key: "Libya"},
        { key: "Liechtenstein"},
        { key: "Lithuania"},
        { key: "Luxembourg"},
        { key: "Macao"},
        { key: "Macedonia, the Former Yugoslav Republic of"},
        { key: "Madagascar"},
        { key: "Malawi"},
        { key: "Malaysia"},
        { key: "Maldives"},
        { key: "Mali"},
        { key: "Malta"},
        { key: "Marshall Islands"},
        { key: "Martinique"},
        { key: "Mauritania"},
        { key: "Mauritius"},
        { key: "Mayotte"},
        { key: "Mexico"},
        { key: "Micronesia, Federated States of"},
        { key: "Moldova, Republic of"},
        { key: "Monaco"},
        { key: "Mongolia"},
        { key: "Montenegro"},
        { key: "Montserrat"},
        { key: "Morocco"},
        { key: "Mozambique"},
        { key: "Myanmar"},
        { key: "Namibia"},
        { key: "Nauru"},
        { key: "Nepal"},
        { key: "Netherlands"},
        { key: "New Caledonia"},
        { key: "New Zealand"},
        { key: "Nicaragua"},
        { key: "Niger"},
        { key: "Nigeria"},
        { key: "Niue"},
        { key: "Norfolk Island"},
        { key: "Northern Mariana Islands"},
        { key: "Norway"},
        { key: "Oman"},
        { key: "Pakistan"},
        { key: "Palau"},
        { key: "Palestine, State of"},
        { key: "Panama"},
        { key: "Papua New Guinea"},
        { key: "Paraguay"},
        { key: "Peru"},
        { key: "Philippines"},
        { key: "Pitcairn"},
        { key: "Poland"},
        { key: "Portugal"},
        { key: "Puerto Rico"},
        { key: "Qatar"},
        { key: "Réunion"},
        { key: "Romania"},
        { key: "Russian Federation"},
        { key: "Rwanda"},
        { key: "Saint Barthélemy"},
        { key: "Saint Helena, Ascension and Tristan da Cunha"},
        { key: "Saint Kitts and Nevis"},
        { key: "Saint Lucia"},
        { key: "Saint Martin (French part)"},
        { key: "Saint Pierre and Miquelon"},
        { key: "Saint Vincent and the Grenadines"},
        { key: "Samoa"},
        { key: "San Marino"},
        { key: "Sao Tome and Principe"},
        { key: "Saudi Arabia"},
        { key: "Senegal"},
        { key: "Serbia"},
        { key: "Seychelles"},
        { key: "Sierra Leone"},
        { key: "Singapore"},
        { key: "Sint Maarten (Dutch part)"},
        { key: "Slovakia"},
        { key: "Slovenia"},
        { key: "Solomon Islands"},
        { key: "Somalia"},
        { key: "South Africa"},
        { key: "South Georgia and the South Sandwich Islands"},
        { key: "South Sudan"},
        { key: "Spain"},
        { key: "Sri Lanka"},
        { key: "Sudan"},
        { key: "Suriname"},
        { key: "Svalbard and Jan Mayen"},
        { key: "Swaziland"},
        { key: "Sweden"},
        { key: "Switzerland"},
        { key: "Syrian Arab Republic"},
        { key: "Taiwan, Province of China"},
        { key: "Tajikistan"},
        { key: "Tanzania, United Republic of"},
        { key: "Thailand"},
        { key: "Timor-Leste"},
        { key: "Togo"},
        { key: "Tokelau"},
        { key: "Tonga"},
        { key: "Trinidad and Tobago"},
        { key: "Tunisia"},
        { key: "Turkey"},
        { key: "Turkmenistan"},
        { key: "Turks and Caicos Islands"},
        { key: "Tuvalu"},
        { key: "Uganda"},
        { key: "Ukraine"},
        { key: "United Arab Emirates"},
        { key: "United Kingdom"},
        { key: "United States"},
        { key: "United States Minor Outlying Islands"},
        { key: "Uruguay"},
        { key: "Uzbekistan"},
        { key: "Vanuatu"},
        { key: "Venezuela, Bolivarian Republic of"},
        { key: "Viet Nam"},
        { key: "Virgin Islands, British"},
        { key: "Virgin Islands, U.S."},
        { key: "Wallis and Futuna"},
        { key: "Western Sahara"},
        { key: "Yemen"},
        { key: "Zambia"},
        { key: "Zimbabwe"},


    ]
}
