export const Warnings = {
    FailedToFindChocolate : "We couldn\'t find this chocolate",
    HelpFindChocolate : "Help us out by adding this new chocolate to our database!",
    ConfirmDeletion : "Are you sure you want to delete this item?",
    ErrorGettingImage : "An error occurred when we attempted to get your image",
    PasswordsDontMatch : "Passwords do not match", 
};

export const PrivacyPolicyUrl = "https://app.termly.io/document/privacy-policy/21cb7adf-4c06-44f1-8af7-7e523f004ef7";

export const StringConcatenations = {
    Prefix: "BarcodeType_",
};

export const DeliveryMethodDisplayText = {
    "pickup": "Pickup",
    "shipping": "Shipping"
};

export const Colors = {
    Primary: "#4B006E",
    Secondary: "white"
};

export const Months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
];

export const OurStoryText = 
    `\"During my senior year at Harvard University, I took Professor Carla Martin’s Chocolate Class: Chocolate, Culture, and Politics of Food, which forever changed the way I see fine chocolate. I learned not only about the wonders of chocolate, such as its ancient and rich history and the nuanced ways of appraising it, but also about the ugly truths hiding within the cacao industry’s supply chain today: child labor, wage-shortening, and other forms of exploitation and injustice. As a consumer, I wanted to become more intentional about where I purchased chocolate, but didn’t know how – especially when these problems felt so far away in countries such as Mexico, Coitre Voir, and Nigeria.

So I set out to empower myself (and others) to make more informed decisions about the chocolate we consume, and this was the beginning of Molinillo. At Molinillo, our mission is to create transparency around ethically sourced chocolate and a fairer world for the cacao farmers and workers who make our lives more delicious.\"`;

export const CountryCodeMappings = {
    "AFGHANISTAN": "AF",
    "ÅLAND ISLANDS": "AX",
    "ALBANIA": "AL",
    "ALGERIA": "DZ",
    "AMERICAN SAMOA": "AS",
    "ANDORRA": "AD",
    "ANGOLA": "AO",
    "ANGUILLA": "AI",
    "ANTARCTICA": "AQ",
    "ANTIGUA AND BARBUDA": "AG",
    "ARGENTINA": "AR",
    "ARMENIA": "AM",
    "ARUBA": "AW",
    "AUSTRALIA": "AU",
    "AUSTRIA": "AT",
    "AZERBAIJAN": "AZ",
    "BAHAMAS": "BS",
    "BAHRAIN": "BH",
    "BANGLADESH": "BD",
    "BARBADOS": "BB",
    "BELARUS": "BY",
    "BELGIUM": "BE",
    "BELIZE": "BZ",
    "BENIN": "BJ",
    "BERMUDA": "BM",
    "BHUTAN": "BT",
    "BOLIVIA, PLURINATIONAL STATE OF": "BO",
    "BONAIRE, SINT EUSTATIUS AND SABA": "BQ",
    "BOSNIA AND HERZEGOVINA": "BA",
    "BOTSWANA": "BW",
    "BOUVET ISLAND": "BV",
    "BRAZIL": "BR",
    "BRITISH INDIAN OCEAN TERRITORY": "IO",
    "BRUNEI DARUSSALAM": "BN",
    "BULGARIA": "BG",
    "BURKINA FASO": "BF",
    "BURUNDI": "BI",
    "CAMBODIA": "KH",
    "CAMEROON": "CM",
    "CANADA": "CA",
    "CAPE VERDE": "CV",
    "CAYMAN ISLANDS": "KY",
    "CENTRAL AFRICAN REPUBLIC": "CF",
    "CHAD": "TD",
    "CHILE": "CL",
    "CHINA": "CN",
    "CHRISTMAS ISLAND": "CX",
    "COCOS (KEELING) ISLANDS": "CC",
    "COLOMBIA": "CO",
    "COMOROS": "KM",
    "CONGO": "CG",
    "CONGO, THE DEMOCRATIC REPUBLIC OF THE": "CD",
    "COOK ISLANDS": "CK",
    "COSTA RICA": "CR",
    "CÔTE D'IVOIRE": "CI",
    "CROATIA": "HR",
    "CUBA": "CU",
    "CURAÇAO": "CW",
    "CYPRUS": "CY",
    "CZECH REPUBLIC": "CZ",
    "DENMARK": "DK",
    "DJIBOUTI": "DJ",
    "DOMINICA": "DM",
    "DOMINICAN REPUBLIC": "DO",
    "ECUADOR": "EC",
    "EGYPT": "EG",
    "EL SALVADOR": "SV",
    "EQUATORIAL GUINEA": "GQ",
    "ERITREA": "ER",
    "ESTONIA": "EE",
    "ETHIOPIA": "ET",
    "FALKLAND ISLANDS (MALVINAS)": "FK",
    "FAROE ISLANDS": "FO",
    "FIJI": "FJ",
    "FINLAND": "FI",
    "FRANCE": "FR",
    "FRENCH GUIANA": "GF",
    "FRENCH POLYNESIA": "PF",
    "FRENCH SOUTHERN TERRITORIES": "TF",
    "GABON": "GA",
    "GAMBIA": "GM",
    "GEORGIA": "GE",
    "GERMANY": "DE",
    "GHANA": "GH",
    "GIBRALTAR": "GI",
    "GREECE": "GR",
    "GREENLAND": "GL",
    "GRENADA": "GD",
    "GUADELOUPE": "GP",
    "GUAM": "GU",
    "GUATEMALA": "GT",
    "GUERNSEY": "GG",
    "GUINEA": "GN",
    "GUINEA-BISSAU": "GW",
    "GUYANA": "GY",
    "HAITI": "HT",
    "HEARD ISLAND AND MCDONALD ISLANDS": "HM",
    "HOLY SEE (VATICAN CITY STATE)": "VA",
    "HONDURAS": "HN",
    "HONG KONG": "HK",
    "HUNGARY": "HU",
    "ICELAND": "IS",
    "INDIA": "IN",
    "INDONESIA": "ID",
    "IRAN, ISLAMIC REPUBLIC OF": "IR",
    "IRAQ": "IQ",
    "IRELAND": "IE",
    "ISLE OF MAN": "IM",
    "ISRAEL": "IL",
    "ITALY": "IT",
    "JAMAICA": "JM",
    "JAPAN": "JP",
    "JERSEY": "JE",
    "JORDAN": "JO",
    "KAZAKHSTAN": "KZ",
    "KENYA": "KE",
    "KIRIBATI": "KI",
    "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": "KP",
    "KOREA, REPUBLIC OF": "KR",
    "KUWAIT": "KW",
    "KYRGYZSTAN": "KG",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": "LA",
    "LATVIA": "LV",
    "LEBANON": "LB",
    "LESOTHO": "LS",
    "LIBERIA": "LR",
    "LIBYA": "LY",
    "LIECHTENSTEIN": "LI",
    "LITHUANIA": "LT",
    "LUXEMBOURG": "LU",
    "MACAO": "MO",
    "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF": "MK",
    "MADAGASCAR": "MG",
    "MALAWI": "MW",
    "MALAYSIA": "MY",
    "MALDIVES": "MV",
    "MALI": "ML",
    "MALTA": "MT",
    "MARSHALL ISLANDS": "MH",
    "MARTINIQUE": "MQ",
    "MAURITANIA": "MR",
    "MAURITIUS": "MU",
    "MAYOTTE": "YT",
    "MEXICO": "MX",
    "MICRONESIA, FEDERATED STATES OF": "FM",
    "MOLDOVA, REPUBLIC OF": "MD",
    "MONACO": "MC",
    "MONGOLIA": "MN",
    "MONTENEGRO": "ME",
    "MONTSERRAT": "MS",
    "MOROCCO": "MA",
    "MOZAMBIQUE": "MZ",
    "MYANMAR": "MM",
    "NAMIBIA": "NA",
    "NAURU": "NR",
    "NEPAL": "NP",
    "NETHERLANDS": "NL",
    "NEW CALEDONIA": "NC",
    "NEW ZEALAND": "NZ",
    "NICARAGUA": "NI",
    "NIGER": "NE",
    "NIGERIA": "NG",
    "NIUE": "NU",
    "NORFOLK ISLAND": "NF",
    "NORTHERN MARIANA ISLANDS": "MP",
    "NORWAY": "NO",
    "OMAN": "OM",
    "PAKISTAN": "PK",
    "PALAU": "PW",
    "PALESTINE, STATE OF": "PS",
    "PANAMA": "PA",
    "PAPUA NEW GUINEA": "PG",
    "PARAGUAY": "PY",
    "PERU": "PE",
    "PHILIPPINES": "PH",
    "PITCAIRN": "PN",
    "POLAND": "PL",
    "PORTUGAL": "PT",
    "PUERTO RICO": "PR",
    "QATAR": "QA",
    "RÉUNION": "RE",
    "ROMANIA": "RO",
    "RUSSIAN FEDERATION": "RU",
    "RWANDA": "RW",
    "SAINT BARTHÉLEMY": "BL",
    "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA": "SH",
    "SAINT KITTS AND NEVIS": "KN",
    "SAINT LUCIA": "LC",
    "SAINT MARTIN (FRENCH PART)": "MF",
    "SAINT PIERRE AND MIQUELON": "PM",
    "SAINT VINCENT AND THE GRENADINES": "VC",
    "SAMOA": "WS",
    "SAN MARINO": "SM",
    "SAO TOME AND PRINCIPE": "ST",
    "SAUDI ARABIA": "SA",
    "SENEGAL": "SN",
    "SERBIA": "RS",
    "SEYCHELLES": "SC",
    "SIERRA LEONE": "SL",
    "SINGAPORE": "SG",
    "SINT MAARTEN (DUTCH PART)": "SX",
    "SLOVAKIA": "SK",
    "SLOVENIA": "SI",
    "SOLOMON ISLANDS": "SB",
    "SOMALIA": "SO",
    "SOUTH AFRICA": "ZA",
    "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS": "GS",
    "SOUTH SUDAN": "SS",
    "SPAIN": "ES",
    "SRI LANKA": "LK",
    "SUDAN": "SD",
    "SURINAME": "SR",
    "SVALBARD AND JAN MAYEN": "SJ",
    "SWAZILAND": "SZ",
    "SWEDEN": "SE",
    "SWITZERLAND": "CH",
    "SYRIAN ARAB REPUBLIC": "SY",
    "TAIWAN, PROVINCE OF CHINA": "TW",
    "TAJIKISTAN": "TJ",
    "TANZANIA, UNITED REPUBLIC OF": "TZ",
    "THAILAND": "TH",
    "TIMOR-LESTE": "TL",
    "TOGO": "TG",
    "TOKELAU": "TK",
    "TONGA": "TO",
    "TRINIDAD AND TOBAGO": "TT",
    "TUNISIA": "TN",
    "TURKEY": "TR",
    "TURKMENISTAN": "TM",
    "TURKS AND CAICOS ISLANDS": "TC",
    "TUVALU": "TV",
    "UGANDA": "UG",
    "UKRAINE": "UA",
    "UNITED ARAB EMIRATES": "AE",
    "UNITED KINGDOM": "GB",
    "UNITED STATES": "US",
    "UNITED STATES MINOR OUTLYING ISLANDS": "UM",
    "URUGUAY": "UY",
    "UZBEKISTAN": "UZ",
    "VANUATU": "VU",
    "VENEZUELA, BOLIVARIAN REPUBLIC OF": "VE",
    "VIET NAM": "VN",
    "VIRGIN ISLANDS, BRITISH": "VG",
    "VIRGIN ISLANDS, U.S.": "VI",
    "WALLIS AND FUTUNA": "WF",
    "WESTERN SAHARA": "EH",
    "YEMEN": "YE",
    "ZAMBIA": "ZM",
    "ZIMBABWE": "ZW"
};


export const dialogOptionsDatasets = {
    "cacaoVariety" : [
        { key: '*Cacao not mentioned' }, 
        { key: 'Criollo' }, 
        { key: 'Forastero' }, 
        { key: 'Trinitario' }, 
        { key: 'Other' }
    ],

    "countryOfOrigin" : [
        { key: "AFGHANISTAN"},
        { key: "ÅLAND ISLANDS"},
        { key: "ALBANIA"},
        { key: "ALGERIA"},
        { key: "AMERICAN SAMOA"},
        { key: "ANDORRA"},
        { key: "ANGOLA"},
        { key: "ANGUILLA"},
        { key: "ANTARCTICA"},
        { key: "ANTIGUA AND BARBUDA"},
        { key: "ARGENTINA"},
        { key: "ARMENIA"},
        { key: "ARUBA"},
        { key: "AUSTRALIA"},
        { key: "AUSTRIA"},
        { key: "AZERBAIJAN"},
        { key: "BAHRAIN"},
        { key: "BAHAMAS"},
        { key: "BANGLADESH"},
        { key: "BARBADOS"},
        { key: "BELARUS"},
        { key: "BELGIUM"},
        { key: "BELIZE"},
        { key: "BENIN"},
        { key: "BERMUDA"},
        { key: "BHUTAN"},
        { key: "BOLIVIA, PLURINATIONAL STATE OF"},
        { key: "BONAIRE, SINT EUSTATIUS AND SABA"},
        { key: "BOSNIA AND HERZEGOVINA"},
        { key: "BOTSWANA"},
        { key: "BOUVET ISLAND"},
        { key: "BRAZIL"},
        { key: "BRITISH INDIAN OCEAN TERRITORY"},
        { key: "BRUNEI DARUSSALAM"},
        { key: "BULGARIA"},
        { key: "BURKINA FASO"},
        { key: "BURUNDI"},
        { key: "CAMBODIA"},
        { key: "CAMEROON"},
        { key: "CANADA"},
        { key: "CAPE VERDE"},
        { key: "CAYMAN ISLANDS"},
        { key: "CENTRAL AFRICAN REPUBLIC"},
        { key: "CHAD"},
        { key: "CHILE"},
        { key: "CHINA"},
        { key: "CHRISTMAS ISLAND"},
        { key: "COCOS (KEELING) ISLANDS"},
        { key: "COLOMBIA"},
        { key: "COMOROS"},
        { key: "CONGO"},
        { key: "CONGO, THE DEMOCRATIC REPUBLIC OF THE"},
        { key: "COOK ISLANDS"},
        { key: "COSTA RICA"},
        { key: "CÔTE D'IVOIRE"},
        { key: "CROATIA"},
        { key: "CUBA"},
        { key: "CURAÇAO"},
        { key: "CYPRUS"},
        { key: "CZECH REPUBLIC"},
        { key: "DENMARK"},
        { key: "DJIBOUTI"},
        { key: "DOMINICA"},
        { key: "DOMINICAN REPUBLIC"},
        { key: "ECUADOR"},
        { key: "EGYPT"},
        { key: "EL SALVADOR"},
        { key: "EQUATORIAL GUINEA"},
        { key: "ERITREA"},
        { key: "ESTONIA"},
        { key: "ETHIOPIA"},
        { key: "FALKLAND ISLANDS (MALVINAS)"},
        { key: "FAROE ISLANDS"},
        { key: "FIJI"},
        { key: "FINLAND"},
        { key: "FRANCE"},
        { key: "FRENCH GUIANA"},
        { key: "FRENCH POLYNESIA"},
        { key: "FRENCH SOUTHERN TERRITORIES"},
        { key: "GABON"},
        { key: "GAMBIA"},
        { key: "GEORGIA"},
        { key: "GERMANY"},
        { key: "GHANA"},
        { key: "GIBRALTAR"},
        { key: "GREECE"},
        { key: "GREENLAND"},
        { key: "GRENADA"},
        { key: "GUADELOUPE"},
        { key: "GUAM"},
        { key: "GUATEMALA"},
        { key: "GUERNSEY"},
        { key: "GUINEA"},
        { key: "GUINEA-BISSAU"},
        { key: "GUYANA"},
        { key: "HAITI"},
        { key: "HEARD ISLAND AND MCDONALD ISLANDS"},
        { key: "HOLY SEE (VATICAN CITY STATE)"},
        { key: "HONDURAS"},
        { key: "HONG KONG"},
        { key: "HUNGARY"},
        { key: "ICELAND"},
        { key: "INDIA"},
        { key: "INDONESIA"},
        { key: "IRAN, ISLAMIC REPUBLIC OF"},
        { key: "IRAQ"},
        { key: "IRELAND"},
        { key: "ISLE OF MAN"},
        { key: "ISRAEL"},
        { key: "ITALY"},
        { key: "JAMAICA"},
        { key: "JAPAN"},
        { key: "JERSEY"},
        { key: "JORDAN"},
        { key: "KAZAKHSTAN"},
        { key: "KENYA"},
        { key: "KIRIBATI"},
        { key: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"},
        { key: "KOREA, REPUBLIC OF"},
        { key: "KUWAIT"},
        { key: "KYRGYZSTAN"},
        { key: "LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
        { key: "LATVIA"},
        { key: "LEBANON"},
        { key: "LESOTHO"},
        { key: "LIBERIA"},
        { key: "LIBYA"},
        { key: "LIECHTENSTEIN"},
        { key: "LITHUANIA"},
        { key: "LUXEMBOURG"},
        { key: "MACAO"},
        { key: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"},
        { key: "MADAGASCAR"},
        { key: "MALAWI"},
        { key: "MALAYSIA"},
        { key: "MALDIVES"},
        { key: "MALI"},
        { key: "MALTA"},
        { key: "MARSHALL ISLANDS"},
        { key: "MARTINIQUE"},
        { key: "MAURITANIA"},
        { key: "MAURITIUS"},
        { key: "MAYOTTE"},
        { key: "MEXICO"},
        { key: "MICRONESIA, FEDERATED STATES OF"},
        { key: "MOLDOVA, REPUBLIC OF"},
        { key: "MONACO"},
        { key: "MONGOLIA"},
        { key: "MONTENEGRO"},
        { key: "MONTSERRAT"},
        { key: "MOROCCO"},
        { key: "MOZAMBIQUE"},
        { key: "MYANMAR"},
        { key: "NAMIBIA"},
        { key: "NAURU"},
        { key: "NEPAL"},
        { key: "NETHERLANDS"},
        { key: "NEW CALEDONIA"},
        { key: "NEW ZEALAND"},
        { key: "NICARAGUA"},
        { key: "NIGER"},
        { key: "NIGERIA"},
        { key: "NIUE"},
        { key: "NORFOLK ISLAND"},
        { key: "NORTHERN MARIANA ISLANDS"},
        { key: "NORWAY"},
        { key: "OMAN"},
        { key: "PAKISTAN"},
        { key: "PALAU"},
        { key: "PALESTINE, STATE OF"},
        { key: "PANAMA"},
        { key: "PAPUA NEW GUINEA"},
        { key: "PARAGUAY"},
        { key: "PERU"},
        { key: "PHILIPPINES"},
        { key: "PITCAIRN"},
        { key: "POLAND"},
        { key: "PORTUGAL"},
        { key: "PUERTO RICO"},
        { key: "QATAR"},
        { key: "RÉUNION"},
        { key: "ROMANIA"},
        { key: "RUSSIAN FEDERATION"},
        { key: "RWANDA"},
        { key: "SAINT BARTHÉLEMY"},
        { key: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"},
        { key: "SAINT KITTS AND NEVIS"},
        { key: "SAINT LUCIA"},
        { key: "SAINT MARTIN (FRENCH PART)"},
        { key: "SAINT PIERRE AND MIQUELON"},
        { key: "SAINT VINCENT AND THE GRENADINES"},
        { key: "SAMOA"},
        { key: "SAN MARINO"},
        { key: "SAO TOME AND PRINCIPE"},
        { key: "SAUDI ARABIA"},
        { key: "SENEGAL"},
        { key: "SERBIA"},
        { key: "SEYCHELLES"},
        { key: "SIERRA LEONE"},
        { key: "SINGAPORE"},
        { key: "SINT MAARTEN (DUTCH PART)"},
        { key: "SLOVAKIA"},
        { key: "SLOVENIA"},
        { key: "SOLOMON ISLANDS"},
        { key: "SOMALIA"},
        { key: "SOUTH AFRICA"},
        { key: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"},
        { key: "SOUTH SUDAN"},
        { key: "SPAIN"},
        { key: "SRI LANKA"},
        { key: "SUDAN"},
        { key: "SURINAME"},
        { key: "SVALBARD AND JAN MAYEN"},
        { key: "SWAZILAND"},
        { key: "SWEDEN"},
        { key: "SWITZERLAND"},
        { key: "SYRIAN ARAB REPUBLIC"},
        { key: "TAIWAN, PROVINCE OF CHINA"},
        { key: "TAJIKISTAN"},
        { key: "TANZANIA, UNITED REPUBLIC OF"},
        { key: "THAILAND"},
        { key: "TIMOR-LESTE"},
        { key: "TOGO"},
        { key: "TOKELAU"},
        { key: "TONGA"},
        { key: "TRINIDAD AND TOBAGO"},
        { key: "TUNISIA"},
        { key: "TURKEY"},
        { key: "TURKMENISTAN"},
        { key: "TURKS AND CAICOS ISLANDS"},
        { key: "TUVALU"},
        { key: "UGANDA"},
        { key: "UKRAINE"},
        { key: "UNITED ARAB EMIRATES"},
        { key: "UNITED KINGDOM"},
        { key: "UNITED STATES"},
        { key: "UNITED STATES MINOR OUTLYING ISLANDS"},
        { key: "URUGUAY"},
        { key: "UZBEKISTAN"},
        { key: "VANUATU"},
        { key: "VENEZUELA, BOLIVARIAN REPUBLIC OF"},
        { key: "VIET NAM"},
        { key: "VIRGIN ISLANDS, BRITISH"},
        { key: "VIRGIN ISLANDS, U.S."},
        { key: "WALLIS AND FUTUNA"},
        { key: "WESTERN SAHARA"},
        { key: "YEMEN"},
        { key: "ZAMBIA"},
        { key: "ZIMBABWE"},
    ],

    USStates: [
        {key: "AL"},
        {key: "AK"},
        {key: "AR"},
        {key: "AZ"},
        {key: "CA"},
        {key: "CO"},
        {key: "CT"},
        {key: "DE"},
        {key: "FL"},
        {key: "GA"},
        {key: "HI"},
        {key: "IA"},
        {key: "ID"},
        {key: "IL"},
        {key: "IN"},
        {key: "KS"},
        {key: "KY"},
        {key: "LA"},
        {key: "MA"},
        {key: "MD"},
        {key: "ME"},
        {key: "MI"},
        {key: "MN"},
        {key: "MO"},
        {key: "MS"},
        {key: "MT"},
        {key: "NC"},
        {key: "ND"},
        {key: "NE"},
        {key: "NH"},
        {key: "NJ"},
        {key: "NM"},
        {key: "NV"},
        {key: "NY"},
        {key: "OH"},
        {key: "OK"},
        {key: "OR"},
        {key: "PA"},
        {key: "RI"},
        {key: "SC"},
        {key: "SD"},
        {key: "TN"},
        {key: "TX"},
        {key: "UT"},
        {key: "VA"},
        {key: "VT"},
        {key: "WA"},
        {key: "WV"},
        {key: "WI"},
        {key: "WY"},
    ]
};
